title: SocialConnect
email: talk@dmtry.me
description: "SocialConnect/Auth is modern open-source social sign library for PHP."
baseurl: ""
url: "https://socialconnect.lowl.io"
twitter_username: ovrweb
github_username: ovr

author:
  twitter: ovrweb

search_enabled: true


plugins:
  - jekyll-feed
  - jekyll-analytics
  - jekyll-sitemap
  - jekyll-seo-tag

markdown: kramdown
theme: just-the-docs

jekyll_analytics:
  GoogleAnalytics:
    id: UA-20503308-12
    anonymizeIp: false
